45 to be merged
nashville-software-school/client-side-mastery pull request #207
Opened 2020-12-21 21:34 UTC by jisie

This a branch made off of cohort-45 branch so that the master branch can be updated.

2020-12-23 20:54 UTC, stevebrownlee commented
:shipit:

2020-12-24 15:35 UTC, askingalot requested changes
I've left a few comments. Some of them are opinions, Some of them are probably better resolved in future changes and shouldn't stop the merge, but a couple should be addressed here. I think those will be obvious, but I'm happy to talk about it.

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/AUTHENTICATION.md
> +    <Route
It seems a little weird to use a `render` prop here and to not have a `path` prop

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/DATA_PROVIDER.md
> +Here's an example vanilla JavaScript code for a data provider.
"Here's an example vanilla JavaScript **module** for a data provider."

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/DATA_PROVIDER.md
> +Next, you will use the State hook to define a variable that holds the state of the component, **and** a function that updates it.
"...you will use the `useState()` hook..."

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/DYNAMIC_ROUTING.md
These lines should be removed.

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/EDIT.md
> +export const AnimalForm = () => {
As we discussed, this the Add and Edit forms should be different components.

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/FORMS_USEREF.md
>  * useRef()
As we discussed, we should use controlled components whenever possible.

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/FORMS_USEREF.md
> +<<<<<<< HEAD
Merge issue

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/FORMS_USEREF.md
> +<<<<<<< HEAD
Merge issue

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/LIST_USECONTEXT.md
> +In the above component, you will notice a 2 new hooks: `useContext` and `useEffect`.
two

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/LIST_USECONTEXT.md
> +<AnimalProvider>
Are we going to leave these providers around the routes, or use global providers in `App.js`?

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/ROUTING.md
> +```
add `jsx`

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/ROUTING.md
>  ```js
jsx

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/scripts/auth.sh
> +                        .then(_ => _.json())
replace `_` with `res` or `resp`

2020-12-24 15:35 UTC, askingalot commented on book-4-nashville-kennels/chapters/scripts/auth.sh
> +                            if (createdUser.hasOwnProperty("id")) {
I don't understand this `if`

2020-12-29 21:19 UTC, JoeShep commented
Thanks for the thorough review, @askingalot. No further comments from me at this time.

2020-12-31 08:30 UTC, merged