updated cohort 47 organization
nashville-software-school/client-side-mastery pull request #268
Opened 2021-07-07 20:13 UTC by brendalong

2021-07-16 20:50 UTC, lcurtis4 commented
👍

2021-07-22 16:28 UTC, askingalot requested changes
Only one real issue. The rest are just comments / questions

2021-07-22 16:28 UTC, askingalot commented on book-4-nashville-kennels/chapters/AUTHENTICATION.md
> +    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nss-day-cohort-47/client-side-mastery/master/book-4-nashville-kennels/chapters/scripts/auth.sh)"
this URL will need to be updated

2021-07-22 16:28 UTC, askingalot commented on book-4-nashville-kennels/chapters/COMPONENT_STYLING.md
> +# Modular CSS for React Components
Are we using this file?

2021-07-22 16:28 UTC, askingalot commented on book-4-nashville-kennels/chapters/DOCKER_INTRO.md
> +## Coming Soon
How soon?

2021-07-22 16:31 UTC, merged