New book 1 about debugging, earlier fetch, and remove book 6
nashville-software-school/client-side-mastery pull request #349
Opened 2023-08-16 20:30 UTC by stevebrownlee

2023-08-22 15:07 UTC, SamThrasher96 approved these changes

2023-08-22 15:08 UTC, SamThrasher96 approved these changes

2023-10-11 16:11 UTC, joshdbarton requested changes

2023-10-11 16:13 UTC, joshdbarton commented on book-0-installations/chapters/GETTING_STARTED_WINDOWS_OLD.md
> +/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nashville-software-school/client-side-mastery/cohort-64/book-0-installations/chapters/scripts/installs-wsl.sh)"
Looks like this one might be obsolete

2023-11-06 14:01 UTC, merged